# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BreakingNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BreakingNews
pod 'Alamofire', '~>4.7'
pod 'DocumentClassifier', '1.0.0'
pod 'Kingfisher', '4.7.0'
  target 'BreakingNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreakingNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
